ports:
- port: 1234
  onOpen: open-preview
- port: 3000
  onOpen: ignore
tasks:
- init: npm install
  command: AWS_EXECUTION_ENV=true npm run sb
- openMode: split-right
  command: LAMBDA_URL=`gp url 3000` npm run sf
